# Generated by Django 4.0.4 on 2023-08-18 19:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_alter_project_project_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
