# Generated by Django 4.0.4 on 2023-08-19 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_useraccount_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='author',
            field=models.CharField(max_length=100, unique=True),
        ),
    ]
