# Generated by Django 4.0.4 on 2023-08-19 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_alter_post_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='post',
            name='post_id',
            field=models.CharField(blank=True, max_length=20, primary_key=True, serialize=False, unique=True),
        ),
    ]
