# Generated by Django 4.0.4 on 2023-08-19 17:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0009_project_contact_project_image_src_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='content',
            new_name='description',
        ),
    ]
