# Generated by Django 4.0.4 on 2023-08-19 17:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0010_rename_content_project_description'),
    ]

    operations = [
        migrations.RenameField(
            model_name='project',
            old_name='type_project',
            new_name='type',
        ),
    ]
