# Generated by Django 4.2.4 on 2023-08-21 12:41

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0012_useraccount_user_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='useraccount',
            name='user_id',
            field=models.UUIDField(default=uuid.uuid4, editable=False, unique=True),
        ),
    ]
