# Generated by Django 4.2.4 on 2023-08-24 10:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0019_image'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Image',
        ),
        migrations.AddField(
            model_name='project',
            name='project_logo',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
