# Generated by Django 4.2.4 on 2023-08-24 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0020_delete_image_project_project_logo'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='project',
            name='project_logo',
        ),
        migrations.AlterField(
            model_name='project',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
