# Generated by Django 4.2.4 on 2023-08-24 10:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0021_remove_project_project_logo_alter_project_image_src'),
    ]

    operations = [
        migrations.AlterField(
            model_name='project',
            name='image_src',
            field=models.ImageField(blank=True, null=True, upload_to='images/projects'),
        ),
    ]
