# Generated by Django 4.2.4 on 2023-09-03 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0027_job'),
    ]

    operations = [
        migrations.CreateModel(
            name='StudentsClub',
            fields=[
                ('students_club_id', models.CharField(max_length=50, primary_key=True, serialize=False, unique=True)),
                ('title', models.CharField(max_length=100)),
                ('related_by_uni', models.JSONField(default=list)),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('members', models.JSONField(default=list)),
                ('author_id', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
    ]
