# Generated by Django 4.2.4 on 2023-09-04 18:18

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0029_studentsclub_image_src'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='created_at',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='project',
            name='dev_stage',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='project',
            name='members',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
