# Generated by Django 4.2.4 on 2023-09-06 18:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0031_post_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='useraccount',
            name='hobbies',
            field=models.JSONField(default=list),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='speciality',
            field=models.CharField(default='Student', max_length=255),
        ),
        migrations.AddField(
            model_name='useraccount',
            name='study_place',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
