# Generated by Django 4.2.4 on 2023-09-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0032_useraccount_hobbies_useraccount_speciality_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='studentsclub',
            name='contact',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
